title: Ghost website
author: Sarfaraz Iraqui
email: sarfarazghlm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A demo website to glance through GitHub Labs courses.
  Going awesome so far. Never thought github could be used for interactive education.

# social links
twitter_username: sziraqui
github_username:  sziraqui

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
